Upgrade to Decidim 0.22.0 (#323)
* Upgrade gems

* Copy migrations

* Force ssl

* Remove humour GIF section from pull request template

* Index already exists, ignore migration

* Remove unrequired overrides after upgrading to v0.22.0

* Make test succeed

As authorizations can be renewed there's now a link in it.

* Use Decidim 0.22.0 from rubygems

* Set POSTGRES_HOST_AUTH_METHOD=trust in docker-compose pg service params

* Change strategy to reset proposal_votes_count

Using the standard Rails `reset_counters` method raises
NoMethodError (undefined method `counter_cache_column' for nil:NilClass)

* Upgrade decidim 0.22 with highlighted private meetings on participatory space details

* Fix bundler version

* Upgrade decidim 0.22 with fix accept invitation to private meetings

* Update to latest from release/0.22-stable

* Remove deprecated override

Co-authored-by: Ivan Molinero <ivan.mr@coditramuntana.com>